// Code generated by goctl. DO NOT EDIT.
// Source: idgen.proto

package idgen

import (
	"context"

	"git.154896.xyz/zhifou/idgen/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty     = pb.Empty
	IdGenResp = pb.IdGenResp

	IdGen interface {
		IdGenServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdGenResp, error)
	}

	defaultIdGen struct {
		cli zrpc.Client
	}
)

func NewIdGen(cli zrpc.Client) IdGen {
	return &defaultIdGen{
		cli: cli,
	}
}

func (m *defaultIdGen) IdGenServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdGenResp, error) {
	client := pb.NewIdGenClient(m.cli.Conn())
	return client.IdGenServer(ctx, in, opts...)
}
