// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: tag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                    // 标签ID
	Tag         string `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`                  // 标签名
	Avatar      string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`            // tag图标
	QuoteNum    int64  `protobuf:"varint,4,opt,name=QuoteNum,proto3" json:"QuoteNum,omitempty"`       // 引用数
	CreatedTime int64  `protobuf:"varint,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` // 创建时间
	UpdatedTime int64  `protobuf:"varint,6,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` // 修改时间
	DeletedTime int64  `protobuf:"varint,7,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` // 删除时间
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *TagInfo) GetQuoteNum() int64 {
	if x != nil {
		return x.QuoteNum
	}
	return 0
}

func (x *TagInfo) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *TagInfo) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *TagInfo) GetDeletedTime() int64 {
	if x != nil {
		return x.DeletedTime
	}
	return 0
}

// 插入一个Tag
type InsertTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    string `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`       // 标签名
	Avatar string `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"` // tag图标
}

func (x *InsertTagReq) Reset() {
	*x = InsertTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTagReq) ProtoMessage() {}

func (x *InsertTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTagReq.ProtoReflect.Descriptor instead.
func (*InsertTagReq) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *InsertTagReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InsertTagReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type InsertTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // 标签ID
}

func (x *InsertTagResp) Reset() {
	*x = InsertTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTagResp) ProtoMessage() {}

func (x *InsertTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTagResp.ProtoReflect.Descriptor instead.
func (*InsertTagResp) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *InsertTagResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 分页获取Tag
type ListTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *ListTagReq) Reset() {
	*x = ListTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagReq) ProtoMessage() {}

func (x *ListTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagReq.ProtoReflect.Descriptor instead.
func (*ListTagReq) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

func (x *ListTagReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTagReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []*TagInfo `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *ListTagResp) Reset() {
	*x = ListTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagResp) ProtoMessage() {}

func (x *ListTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagResp.ProtoReflect.Descriptor instead.
func (*ListTagResp) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{4}
}

func (x *ListTagResp) GetTopics() []*TagInfo {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 获取热点Tag
type ListHotTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"` // 获取hot
}

func (x *ListHotTagReq) Reset() {
	*x = ListHotTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHotTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotTagReq) ProtoMessage() {}

func (x *ListHotTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotTagReq.ProtoReflect.Descriptor instead.
func (*ListHotTagReq) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{5}
}

func (x *ListHotTagReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ListHotTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []*TagInfo `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *ListHotTagResp) Reset() {
	*x = ListHotTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHotTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotTagResp) ProtoMessage() {}

func (x *ListHotTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotTagResp.ProtoReflect.Descriptor instead.
func (*ListHotTagResp) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{6}
}

func (x *ListHotTagResp) GetTopics() []*TagInfo {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 获取最新Tag
type ListNewTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"` // 获取hot
}

func (x *ListNewTagReq) Reset() {
	*x = ListNewTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNewTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewTagReq) ProtoMessage() {}

func (x *ListNewTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewTagReq.ProtoReflect.Descriptor instead.
func (*ListNewTagReq) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{7}
}

func (x *ListNewTagReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ListNewTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []*TagInfo `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *ListNewTagResp) Reset() {
	*x = ListNewTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNewTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewTagResp) ProtoMessage() {}

func (x *ListNewTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewTagResp.ProtoReflect.Descriptor instead.
func (*ListNewTagResp) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{8}
}

func (x *ListNewTagResp) GetTopics() []*TagInfo {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 获取一个Tag详情
type FindOneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FindOneReq) Reset() {
	*x = FindOneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneReq) ProtoMessage() {}

func (x *FindOneReq) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneReq.ProtoReflect.Descriptor instead.
func (*FindOneReq) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{9}
}

func (x *FindOneReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                    // 标签ID
	Tag         string `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`                  // 标签名
	Avatar      string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`            // tag图标
	QuoteNum    int64  `protobuf:"varint,4,opt,name=QuoteNum,proto3" json:"QuoteNum,omitempty"`       // 引用数
	CreatedTime int64  `protobuf:"varint,5,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` // 创建时间
	UpdatedTime int64  `protobuf:"varint,6,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` // 修改时间
	DeletedTime int64  `protobuf:"varint,7,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` // 删除时间
}

func (x *FindOneResp) Reset() {
	*x = FindOneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneResp) ProtoMessage() {}

func (x *FindOneResp) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneResp.ProtoReflect.Descriptor instead.
func (*FindOneResp) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{10}
}

func (x *FindOneResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindOneResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *FindOneResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FindOneResp) GetQuoteNum() int64 {
	if x != nil {
		return x.QuoteNum
	}
	return 0
}

func (x *FindOneResp) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *FindOneResp) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *FindOneResp) GetDeletedTime() int64 {
	if x != nil {
		return x.DeletedTime
	}
	return 0
}

var File_tag_proto protoreflect.FileDescriptor

var file_tag_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x61, 0x67,
	0x22, 0xc5, 0x01, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4e,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4e,
	0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x22, 0x1f, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x33, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x24, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x36, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x6f, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x4e, 0x75, 0x6d, 0x22, 0x36, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0x1c, 0x0a, 0x0a,
	0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0b, 0x46,
	0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4e, 0x75, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x86, 0x02, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x32,
	0x0a, 0x09, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x61, 0x67, 0x12, 0x11, 0x2e, 0x74, 0x61,
	0x67, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x0f,
	0x2e, 0x74, 0x61, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x74, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x12, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48,
	0x6f, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x67, 0x73, 0x12, 0x12, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x74,
	0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData = file_tag_proto_rawDesc
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_proto_rawDescData)
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tag_proto_goTypes = []interface{}{
	(*TagInfo)(nil),        // 0: tag.TagInfo
	(*InsertTagReq)(nil),   // 1: tag.InsertTagReq
	(*InsertTagResp)(nil),  // 2: tag.InsertTagResp
	(*ListTagReq)(nil),     // 3: tag.ListTagReq
	(*ListTagResp)(nil),    // 4: tag.ListTagResp
	(*ListHotTagReq)(nil),  // 5: tag.ListHotTagReq
	(*ListHotTagResp)(nil), // 6: tag.ListHotTagResp
	(*ListNewTagReq)(nil),  // 7: tag.ListNewTagReq
	(*ListNewTagResp)(nil), // 8: tag.ListNewTagResp
	(*FindOneReq)(nil),     // 9: tag.FindOneReq
	(*FindOneResp)(nil),    // 10: tag.FindOneResp
}
var file_tag_proto_depIdxs = []int32{
	0,  // 0: tag.ListTagResp.Topics:type_name -> tag.TagInfo
	0,  // 1: tag.ListHotTagResp.Topics:type_name -> tag.TagInfo
	0,  // 2: tag.ListNewTagResp.Topics:type_name -> tag.TagInfo
	1,  // 3: tag.Tag.InsertTag:input_type -> tag.InsertTagReq
	3,  // 4: tag.Tag.ListTags:input_type -> tag.ListTagReq
	5,  // 5: tag.Tag.ListHotTags:input_type -> tag.ListHotTagReq
	7,  // 6: tag.Tag.ListNewTags:input_type -> tag.ListNewTagReq
	9,  // 7: tag.Tag.FindOne:input_type -> tag.FindOneReq
	2,  // 8: tag.Tag.InsertTag:output_type -> tag.InsertTagResp
	4,  // 9: tag.Tag.ListTags:output_type -> tag.ListTagResp
	6,  // 10: tag.Tag.ListHotTags:output_type -> tag.ListHotTagResp
	8,  // 11: tag.Tag.ListNewTags:output_type -> tag.ListNewTagResp
	10, // 12: tag.Tag.FindOne:output_type -> tag.FindOneResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHotTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHotTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNewTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNewTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_rawDesc = nil
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
