// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: dynamic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	Url   string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Attachment) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 新增动态
type InsertPostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string        `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Contents    string        `protobuf:"bytes,2,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,3,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	Tags        []*Tag        `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *InsertPostReq) Reset() {
	*x = InsertPostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPostReq) ProtoMessage() {}

func (x *InsertPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPostReq.ProtoReflect.Descriptor instead.
func (*InsertPostReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{2}
}

func (x *InsertPostReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsertPostReq) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *InsertPostReq) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *InsertPostReq) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type InsertPostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId      string        `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Contents    string        `protobuf:"bytes,3,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,4,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	Tags        []*Tag        `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedTime int64         `protobuf:"varint,6,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` // 创建时间
	UpdatedTime int64         `protobuf:"varint,7,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` // 修改时间
	DeletedTime int64         `protobuf:"varint,8,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` // 删除时间
	IsDel       bool          `protobuf:"varint,9,opt,name=IsDel,proto3" json:"IsDel,omitempty"`             //是否删除
}

func (x *InsertPostResp) Reset() {
	*x = InsertPostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPostResp) ProtoMessage() {}

func (x *InsertPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPostResp.ProtoReflect.Descriptor instead.
func (*InsertPostResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{3}
}

func (x *InsertPostResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertPostResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsertPostResp) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *InsertPostResp) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *InsertPostResp) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InsertPostResp) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *InsertPostResp) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *InsertPostResp) GetDeletedTime() int64 {
	if x != nil {
		return x.DeletedTime
	}
	return 0
}

func (x *InsertPostResp) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

// 分页获取动态
type GetDynamicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId  string `protobuf:"bytes,2,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageNum int64  `protobuf:"varint,3,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
}

func (x *GetDynamicReq) Reset() {
	*x = GetDynamicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDynamicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicReq) ProtoMessage() {}

func (x *GetDynamicReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicReq.ProtoReflect.Descriptor instead.
func (*GetDynamicReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{4}
}

func (x *GetDynamicReq) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

func (x *GetDynamicReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type GetDynamicResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CommonResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDynamicResp) Reset() {
	*x = GetDynamicResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDynamicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicResp) ProtoMessage() {}

func (x *GetDynamicResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicResp.ProtoReflect.Descriptor instead.
func (*GetDynamicResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{5}
}

func (x *GetDynamicResp) GetData() []*CommonResp {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查询一个
type FindOneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FindOneReq) Reset() {
	*x = FindOneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneReq) ProtoMessage() {}

func (x *FindOneReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneReq.ProtoReflect.Descriptor instead.
func (*FindOneReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{6}
}

func (x *FindOneReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOneResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId      string        `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Contents    string        `protobuf:"bytes,3,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,4,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	Tags        []*Tag        `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedTime int64         `protobuf:"varint,6,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` // 创建时间
	UpdatedTime int64         `protobuf:"varint,7,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` // 修改时间
	DeletedTime int64         `protobuf:"varint,8,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` // 删除时间
	IsDel       bool          `protobuf:"varint,9,opt,name=IsDel,proto3" json:"IsDel,omitempty"`             //是否删除
}

func (x *FindOneResp) Reset() {
	*x = FindOneResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneResp) ProtoMessage() {}

func (x *FindOneResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneResp.ProtoReflect.Descriptor instead.
func (*FindOneResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{7}
}

func (x *FindOneResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindOneResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindOneResp) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *FindOneResp) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *FindOneResp) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FindOneResp) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *FindOneResp) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *FindOneResp) GetDeletedTime() int64 {
	if x != nil {
		return x.DeletedTime
	}
	return 0
}

func (x *FindOneResp) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

// 查询许多
type FindManyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=Ids,proto3" json:"Ids,omitempty"`
}

func (x *FindManyReq) Reset() {
	*x = FindManyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindManyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyReq) ProtoMessage() {}

func (x *FindManyReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyReq.ProtoReflect.Descriptor instead.
func (*FindManyReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{8}
}

func (x *FindManyReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId      string        `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Contents    string        `protobuf:"bytes,3,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,4,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	Tags        []*Tag        `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedTime int64         `protobuf:"varint,6,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"` // 创建时间
	UpdatedTime int64         `protobuf:"varint,7,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"` // 修改时间
	DeletedTime int64         `protobuf:"varint,8,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"` // 删除时间
	IsDel       bool          `protobuf:"varint,9,opt,name=IsDel,proto3" json:"IsDel,omitempty"`             //是否删除
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{9}
}

func (x *CommonResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommonResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommonResp) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *CommonResp) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *CommonResp) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CommonResp) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *CommonResp) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *CommonResp) GetDeletedTime() int64 {
	if x != nil {
		return x.DeletedTime
	}
	return 0
}

func (x *CommonResp) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

type FindManyReqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CommonResp `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *FindManyReqResp) Reset() {
	*x = FindManyReqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindManyReqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyReqResp) ProtoMessage() {}

func (x *FindManyReqResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyReqResp.ProtoReflect.Descriptor instead.
func (*FindManyReqResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{10}
}

func (x *FindManyReqResp) GetData() []*CommonResp {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分页查询某个Tag的全部动态
type QueryTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId   string `protobuf:"bytes,1,opt,name=TagId,proto3" json:"TagId,omitempty"`
	LastId  string `protobuf:"bytes,2,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageNum int64  `protobuf:"varint,3,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
}

func (x *QueryTagReq) Reset() {
	*x = QueryTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagReq) ProtoMessage() {}

func (x *QueryTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagReq.ProtoReflect.Descriptor instead.
func (*QueryTagReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTagReq) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *QueryTagReq) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

func (x *QueryTagReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type QueryTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CommonResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *QueryTagResp) Reset() {
	*x = QueryTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagResp) ProtoMessage() {}

func (x *QueryTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagResp.ProtoReflect.Descriptor instead.
func (*QueryTagResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{12}
}

func (x *QueryTagResp) GetData() []*CommonResp {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分页查询某个User的全部动态
type QueryUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	LastId  string `protobuf:"bytes,2,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageNum int64  `protobuf:"varint,3,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
}

func (x *QueryUserReq) Reset() {
	*x = QueryUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserReq) ProtoMessage() {}

func (x *QueryUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserReq.ProtoReflect.Descriptor instead.
func (*QueryUserReq) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{13}
}

func (x *QueryUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryUserReq) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

func (x *QueryUserReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type QueryUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CommonResp `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *QueryUserResp) Reset() {
	*x = QueryUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserResp) ProtoMessage() {}

func (x *QueryUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserResp.ProtoReflect.Descriptor instead.
func (*QueryUserResp) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{14}
}

func (x *QueryUserResp) GetData() []*CommonResp {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dynamic_proto protoreflect.FileDescriptor

var file_dynamic_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x22, 0x48, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x72, 0x6c, 0x22, 0x31, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x22, 0xa9, 0x02, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73,
	0x44, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c,
	0x22, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x22, 0x39, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1c,
	0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xa6, 0x02, 0x0a,
	0x0b, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x35, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e,
	0x54, 0x61, 0x67, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x49, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x1f, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x6e,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x49, 0x64, 0x73, 0x22, 0xa5, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x20, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x3a,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x0b, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61, 0x67,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x67, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75,
	0x6d, 0x22, 0x37, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x58, 0x0a, 0x0c, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61,
	0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x22, 0x38, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x32, 0xef,
	0x02, 0x0a, 0x07, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x3d, 0x0a, 0x0a, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x16, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x14, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x12, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x15, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamic_proto_rawDescOnce sync.Once
	file_dynamic_proto_rawDescData = file_dynamic_proto_rawDesc
)

func file_dynamic_proto_rawDescGZIP() []byte {
	file_dynamic_proto_rawDescOnce.Do(func() {
		file_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_proto_rawDescData)
	})
	return file_dynamic_proto_rawDescData
}

var file_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dynamic_proto_goTypes = []interface{}{
	(*Attachment)(nil),      // 0: dynamic.Attachment
	(*Tag)(nil),             // 1: dynamic.Tag
	(*InsertPostReq)(nil),   // 2: dynamic.InsertPostReq
	(*InsertPostResp)(nil),  // 3: dynamic.InsertPostResp
	(*GetDynamicReq)(nil),   // 4: dynamic.GetDynamicReq
	(*GetDynamicResp)(nil),  // 5: dynamic.GetDynamicResp
	(*FindOneReq)(nil),      // 6: dynamic.FindOneReq
	(*FindOneResp)(nil),     // 7: dynamic.FindOneResp
	(*FindManyReq)(nil),     // 8: dynamic.FindManyReq
	(*CommonResp)(nil),      // 9: dynamic.CommonResp
	(*FindManyReqResp)(nil), // 10: dynamic.FindManyReqResp
	(*QueryTagReq)(nil),     // 11: dynamic.QueryTagReq
	(*QueryTagResp)(nil),    // 12: dynamic.QueryTagResp
	(*QueryUserReq)(nil),    // 13: dynamic.QueryUserReq
	(*QueryUserResp)(nil),   // 14: dynamic.QueryUserResp
}
var file_dynamic_proto_depIdxs = []int32{
	0,  // 0: dynamic.InsertPostReq.Attachments:type_name -> dynamic.Attachment
	1,  // 1: dynamic.InsertPostReq.Tags:type_name -> dynamic.Tag
	0,  // 2: dynamic.InsertPostResp.Attachments:type_name -> dynamic.Attachment
	1,  // 3: dynamic.InsertPostResp.Tags:type_name -> dynamic.Tag
	9,  // 4: dynamic.GetDynamicResp.data:type_name -> dynamic.CommonResp
	0,  // 5: dynamic.FindOneResp.Attachments:type_name -> dynamic.Attachment
	1,  // 6: dynamic.FindOneResp.Tags:type_name -> dynamic.Tag
	0,  // 7: dynamic.CommonResp.Attachments:type_name -> dynamic.Attachment
	1,  // 8: dynamic.CommonResp.Tags:type_name -> dynamic.Tag
	9,  // 9: dynamic.FindManyReqResp.Data:type_name -> dynamic.CommonResp
	9,  // 10: dynamic.QueryTagResp.data:type_name -> dynamic.CommonResp
	9,  // 11: dynamic.QueryUserResp.Data:type_name -> dynamic.CommonResp
	2,  // 12: dynamic.Dynamic.InsertPost:input_type -> dynamic.InsertPostReq
	4,  // 13: dynamic.Dynamic.GetDynamic:input_type -> dynamic.GetDynamicReq
	6,  // 14: dynamic.Dynamic.FindPost:input_type -> dynamic.FindOneReq
	8,  // 15: dynamic.Dynamic.FindMany:input_type -> dynamic.FindManyReq
	11, // 16: dynamic.Dynamic.QueryTag:input_type -> dynamic.QueryTagReq
	13, // 17: dynamic.Dynamic.QueryUser:input_type -> dynamic.QueryUserReq
	3,  // 18: dynamic.Dynamic.InsertPost:output_type -> dynamic.InsertPostResp
	5,  // 19: dynamic.Dynamic.GetDynamic:output_type -> dynamic.GetDynamicResp
	7,  // 20: dynamic.Dynamic.FindPost:output_type -> dynamic.FindOneResp
	10, // 21: dynamic.Dynamic.FindMany:output_type -> dynamic.FindManyReqResp
	12, // 22: dynamic.Dynamic.QueryTag:output_type -> dynamic.QueryTagResp
	14, // 23: dynamic.Dynamic.QueryUser:output_type -> dynamic.QueryUserResp
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_dynamic_proto_init() }
func file_dynamic_proto_init() {
	if File_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDynamicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDynamicResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindManyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindManyReqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamic_proto_goTypes,
		DependencyIndexes: file_dynamic_proto_depIdxs,
		MessageInfos:      file_dynamic_proto_msgTypes,
	}.Build()
	File_dynamic_proto = out.File
	file_dynamic_proto_rawDesc = nil
	file_dynamic_proto_goTypes = nil
	file_dynamic_proto_depIdxs = nil
}
