// Code generated by goctl. DO NOT EDIT.
// Source: idgen.proto

package server

import (
	"context"

	"git.154896.xyz/zhifou/idgen/internal/logic"
	"git.154896.xyz/zhifou/idgen/internal/svc"
	"git.154896.xyz/zhifou/idgen/pb"
)

type IdGenServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdGenServer
}

func NewIdGenServer(svcCtx *svc.ServiceContext) *IdGenServer {
	return &IdGenServer{
		svcCtx: svcCtx,
	}
}

func (s *IdGenServer) IdGenServer(ctx context.Context, in *pb.Empty) (*pb.IdGenResp, error) {
	l := logic.NewIdGenServerLogic(ctx, s.svcCtx)
	return l.IdGenServer(in)
}
